# Generated by Django 6.1.1 on 2026-09-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(error_messages={'unique': 'Статус с таким именем уже существует.'}, max_length=100, unique=True, verbose_name='Имя'),
        ),
    ]
